import { FlatCompat } from "@eslint/eslintrc";
import { fixupPluginRules } from "@eslint/compat";
import js from "@eslint/js";
import microsoftSdl from "@microsoft/eslint-plugin-sdl";
import tsParser from "@typescript-eslint/parser";
import barrelFiles from "eslint-plugin-barrel-files";
import eslintComments from "eslint-plugin-eslint-comments";
import fileProgress from "eslint-plugin-file-progress";
import github from "eslint-plugin-github";
import importAccess from "eslint-plugin-import-access/flat-config";
import lodashF from "eslint-plugin-lodash-f";
import more from "eslint-plugin-morect";
import antiTrojanCt from "eslint-plugin-anti-trojan-source";
import noSecrets from "eslint-plugin-no-secrets";
import noUnsanitized from "eslint-plugin-no-unsanitized";
import perfectionist from "eslint-plugin-perfectionist";
import * as regexpPlugin from "eslint-plugin-regexp";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import sonarjs from "eslint-plugin-sonarjs";
import tsdoc from "eslint-plugin-tsdoc";
import typescriptEnum from "eslint-plugin-typescript-enum";
import unicorn from "eslint-plugin-unicorn";
import writeGoodComments from "eslint-plugin-write-good-comments";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import path from "node:path";
import { fileURLToPath } from "node:url";
import typescriptEslint from "typescript-eslint";
import jsdoc from "eslint-plugin-jsdoc";
import pluginQuery from "@tanstack/eslint-plugin-query";
import problems from "eslint-config-problems";
import compatPlugin from "eslint-plugin-compat";
import depend from "eslint-plugin-depend";
import fsecond from "eslint-plugin-fsecond-ct";
import jsxA11y from "eslint-plugin-jsx-a11y";
import pluginPromise from "eslint-plugin-promise";
import reactCompiler from "eslint-plugin-react-compiler";
import reactDom from "eslint-plugin-react-dom";
import reactHooks from "eslint-plugin-react-hooks";
import reactHooksExtra from "eslint-plugin-react-hooks-extra";
import reactNamingConvention from "eslint-plugin-react-naming-convention";
import reactPerf from "eslint-plugin-react-perf";
import reactRefresh from "eslint-plugin-react-refresh";
import reactWebApi from "eslint-plugin-react-web-api";
import reactX from "eslint-plugin-react-x";
import ssrFriendly from "eslint-plugin-ssr-friendly";
import reactHookForm from "eslint-plugin-react-hook-form";
import html from "@html-eslint/eslint-plugin";
import observers from "eslint-plugin-observers";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all,
});

export default defineConfig([
    globalIgnores([
        "**/*.js",
        "**/tailwind.config.ts",
        "**/global.t.ts",
        "dist/**/*",
        "eslint.config.mjs",
        "tailwind.config.ts",
        "src/assets/data/*",
        "src/assets/png/*",
        "src/assets/svg/*",
        "src/assets/test/Playground.tsx",
        "*.stories.tsx",
        "src/@lib/generated/**/*",
        "vite.config.ts",
        "postcss.config.mjs",
    ]),
    problems,
    sonarjs.configs.recommended,
    typescriptEslint.configs.recommended,
    perfectionist.configs["recommended-natural"],
    regexpPlugin.configs["flat/recommended"],
    html.configs["flat/recommended"],
    ...microsoftSdl.configs.recommended,
    ...microsoftSdl.configs.node,
    ...microsoftSdl.configs.typescript,
    ...microsoftSdl.configs.common,
    compatPlugin.configs["flat/recommended"],
    ...github.getFlatConfigs().typescript,
    github.getFlatConfigs().recommended,
    github.getFlatConfigs().browser,
    github.getFlatConfigs().react,
    ...pluginQuery.configs["flat/recommended"],
    pluginPromise.configs["flat/recommended"],
    reactCompiler.configs.recommended,
    reactDom.configs.recommended,
    reactHooks.configs.flat["recommended-latest"],
    reactHooksExtra.configs.recommended,
    reactNamingConvention.configs.recommended,
    reactPerf.configs.flat.all,
    reactRefresh.configs.recommended,
    reactWebApi.configs.recommended,
    reactX.configs.recommended,
    depend.configs["flat/recommended"],
    unicorn.configs.recommended,
    {
        extends: compat.extends(
            "problems",
            "plugin:jsx-a11y/recommended",
            "plugin:promise/recommended",
            "plugin:xss/recommended",
            "plugin:redos/recommended",
            "plugin:anti-trojan-source/recommended",
            "plugin:typescript-enum/recommended",
            "plugin:lodash-f/recommended",
            "plugin:redos/recommended",
            "plugin:risxss/recommended",
            "plugin:xss/recommended",
        ),

        plugins: {
            "no-secrets": noSecrets,
            "eslint-comments": eslintComments,
            "simple-import-sort": simpleImportSort,
            tsdoc,
            jsdoc,
            "file-progress": fileProgress,
            more,
            fsecond,
            "write-good-comments": writeGoodComments,
            "no-unsanitized": noUnsanitized,
            "typescript-enum": typescriptEnum,
            "import-access": importAccess,
            "barrel-files": barrelFiles,
            "lodash-f": lodashF,
            "anti-trojan-source": antiTrojanCt,
            "jsx-a11y": jsxA11y,
            "ssr-friendly": fixupPluginRules(ssrFriendly),
            "react-hook-form": fixupPluginRules(reactHookForm),
            observers: observers,
        },

        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.jest,
                ...globals.node,
                JSX: true,
                globalThis: "readonly",
            },

            parser: tsParser,
            ecmaVersion: "latest",
            sourceType: "module",

            parserOptions: {
                project: ["./tsconfig.app.json", "./tsconfig.node.json"],
                tsconfigRootDir: __dirname,
            },
        },

        settings: {
            progress: { hide: false, successMessage: "Lint done..." },

            react: { version: "16.8" },

            jest: { version: 26 },
        },

        rules: {
            "tsdoc/syntax": "error",
            "fsecond/prefer-destructured-optionals": "error",
            "fsecond/valid-event-listener": "error",
            "fsecond/prefer-aliased-path": "error",
            "risxss/catch-potential-xss-vue": "off",
            "ssr-friendly/no-dom-globals-in-module-scope": ["error"],
            "ssr-friendly/no-dom-globals-in-constructor": ["error"],
            "ssr-friendly/no-dom-globals-in-react-cc-render": ["error"],
            "ssr-friendly/no-dom-globals-in-react-fc": ["error"],
            "react-hook-form/destructuring-formstate": ["error"],
            "react-hook-form/no-access-control": ["error"],
            "react-hook-form/no-nested-object-setvalue": ["error"],
            "i18n-text/no-en": "off",
            "for-direction": "error",
            "getter-return": "error",
            "no-async-promise-executor": "error",
            "no-await-in-loop": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": "error",
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-dupe-args": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",

            "no-empty": ["error", { allowEmptyCatch: true }],

            "no-empty-character-class": "error",
            "no-ex-assign": "error",
            "no-extra-semi": "error",
            "no-func-assign": "error",
            "no-import-assign": "error",
            "no-inner-declarations": "error",
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-loss-of-precision": "error",
            "no-misleading-character-class": "error",
            "no-obj-calls": "error",
            "no-promise-executor-return": "error",
            "no-prototype-builtins": "error",
            "no-regex-spaces": "error",
            "no-setter-return": "error",
            "no-sparse-arrays": "error",
            "no-template-curly-in-string": "error",
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "no-unreachable-loop": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "error",
            "no-unsafe-optional-chaining": "error",
            "no-unused-private-class-members": "error",
            "no-useless-backreference": "error",
            "require-atomic-updates": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            "accessor-pairs": "error",
            "array-callback-return": "error",
            "block-scoped-var": "error",
            "class-methods-use-this": "error",

            complexity: ["error", { max: 50 }],

            "consistent-return": "error",
            curly: "error",
            "default-case": "error",
            "default-case-last": "error",
            "default-param-last": "error",
            "dot-location": ["error", "property"],
            "dot-notation": "error",
            eqeqeq: "error",
            "grouped-accessor-pairs": "error",
            "guard-for-in": "error",
            "max-classes-per-file": ["error", 3],
            "no-alert": "error",
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-constructor-return": "error",
            "no-div-regex": "error",
            "no-else-return": "error",
            "no-empty-function": "error",
            "no-empty-pattern": "error",
            camelcase: "off",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-fallthrough": "error",
            "no-floating-decimal": "error",
            "no-global-assign": "error",

            "no-implicit-coercion": ["error", { boolean: false }],

            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-loop-func": "error",
            "no-multi-spaces": "error",
            "no-multi-str": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-nonoctal-decimal-escape": "error",
            "no-octal": "error",
            "no-octal-escape": "error",
            "no-param-reassign": "error",
            "no-proto": "error",
            "no-redeclare": "error",
            "no-restricted-properties": "error",
            "no-return-assign": "error",
            "no-return-await": "off",
            "no-script-url": "error",
            "no-self-assign": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-throw-literal": "error",
            "no-unmodified-loop-condition": "error",
            "no-unused-expressions": "error",
            "no-unused-labels": "error",
            "no-useless-call": "error",
            "no-useless-catch": "error",
            "no-useless-concat": "error",
            "no-useless-escape": "error",
            "no-useless-return": "error",
            "no-void": "error",
            "no-with": "error",
            "prefer-named-capture-group": "error",
            "prefer-object-has-own": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-regex-literals": "error",
            radix: "error",
            "require-await": "error",
            "require-unicode-regexp": "error",
            "vars-on-top": "error",
            "wrap-iife": "error",
            yoda: "error",
            strict: "error",
            "init-declarations": "error",
            "no-delete-var": "error",
            "no-label-var": "error",

            "no-restricted-globals": [
                "error",
                "addEventListener",
                "blur",
                "close",
                "closed",
                "confirm",
                "defaultStatus",
                "defaultstatus",
                "event",
                "external",
                "find",
                "focus",
                "frameElement",
                "frames",
                "history",
                "innerHeight",
                "innerWidth",
                "length",
                "location",
                "locationbar",
                "menubar",
                "moveBy",
                "moveTo",
                "name",
                "onblur",
                "onerror",
                "onfocus",
                "onload",
                "onresize",
                "onunload",
                "open",
                "opener",
                "opera",
                "outerHeight",
                "outerWidth",
                "pageXerrorset",
                "pageYerrorset",
                "parent",
                "print",
                "removeEventListener",
                "resizeBy",
                "resizeTo",
                "screen",
                "screenLeft",
                "screenTop",
                "screenX",
                "screenY",
                "scroll",
                "scrollbars",
                "scrollBy",
                "scrollTo",
                "scrollX",
                "scrollY",
                "self",
                "status",
                "statusbar",
                "stop",
                "toolbar",
                "top",
            ],

            "no-shadow": "error",
            "no-shadow-restricted-names": "error",
            "no-undef-init": "error",

            "no-unused-vars": [
                "error",
                {
                    varsIgnorePattern: "^_",
                    argsIgnorePattern: "^_",
                    destructuredArrayIgnorePattern: "^_",
                },
            ],

            "no-use-before-define": "error",
            "array-bracket-newline": ["error", "consistent"],
            "array-bracket-spacing": ["error", "never"],
            "array-element-newline": ["error", "consistent"],
            "block-spacing": "error",
            "brace-style": "error",
            "capitalized-comments": "error",
            "comma-dangle": ["error", "always-multiline"],
            "comma-spacing": "error",
            "comma-style": "error",
            "computed-property-spacing": "error",
            "consistent-this": "error",
            "eol-last": "error",
            "func-call-spacing": "error",
            "func-name-matching": "error",
            "func-names": "error",

            "func-style": [
                "error",
                "declaration",
                { allowArrowFunctions: true },
            ],

            "id-denylist": "error",

            "id-length": [
                "error",
                {
                    min: 2,
                    exceptions: ["x", "y", "a", "b", "_", "t", "i", "j"],
                    properties: "never",
                },
            ],

            "id-match": "error",
            "jsx-quotes": "error",

            "key-spacing": ["error", { mode: "minimum" }],

            "line-comment-position": "error",

            "lines-around-comment": ["error", { beforeBlockComment: false }],

            "max-depth": ["error", 7],

            "max-len": [
                "error",
                {
                    code: 120,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                    ignoreComments: true,
                    ignoreTrailingComments: true,
                },
            ],

            "max-lines": ["error", { max: 1000 }],

            "max-lines-per-function": [
                "error",
                {
                    max: 1000,
                    skipBlankLines: true,
                    skipComments: true,
                    IIFEs: false,
                },
            ],

            "max-nested-callbacks": "error",

            "max-params": ["error", { max: 9 }],

            "max-statements": ["error", { max: 30 }],

            "max-statements-per-line": ["error", { max: 2 }],

            "multiline-comment-style": "warn",
            "multiline-ternary": "off",
            "new-cap": "error",
            "new-parens": "error",
            "newline-per-chained-call": "error",
            "no-array-constructor": "error",
            "no-bitwise": "error",
            "no-continue": "error",
            "no-inline-comments": "error",
            "no-lonely-if": "error",
            "no-mixed-operators": "error",
            "no-mixed-spaces-and-tabs": "off",
            "no-multi-assign": "error",

            "no-multiple-empty-lines": [
                "error",
                { max: 3, maxBOF: 0, maxEOF: 0 },
            ],

            "no-negated-condition": "error",
            "no-new-object": "error",
            "no-plusplus": "error",
            "no-restricted-syntax": ["error", "WithStatement"],
            "no-tabs": "off",
            "no-trailing-spaces": "error",
            "no-unneeded-ternary": "error",
            "no-whitespace-before-property": "error",
            "nonblock-statement-body-position": "error",
            "object-curly-newline": "error",
            "one-var": ["error", "never"],
            "one-var-declaration-per-line": "error",
            "operator-assignment": "error",
            "operator-linebreak": "error",
            "prefer-exponentiation-operator": "error",
            "prefer-object-spread": "error",

            "quote-props": ["error", "as-needed", { numbers: true }],

            quotes: "error",
            semi: "error",
            "semi-spacing": "error",
            "semi-style": "error",
            "sort-keys": "error",
            "sort-vars": "error",
            "space-before-blocks": "error",
            "space-before-function-paren": "off",
            "space-in-parens": "error",
            "space-infix-ops": "error",
            "space-unary-ops": "error",

            "spaced-comment": [
                "error",
                "always",
                { exceptions: ["/", "*", "-", "* "], markers: ["/", "?"] },
            ],

            "switch-colon-spacing": "error",
            "template-tag-spacing": "error",
            "unicode-bom": "error",
            "wrap-regex": "error",
            "arrow-body-style": ["error", "as-needed"],
            "arrow-parens": ["error", "always"],

            "arrow-spacing": ["error", { before: true, after: true }],

            "constructor-super": "error",
            "generator-star-spacing": ["error", "after"],
            "no-class-assign": "error",

            "no-confusing-arrow": ["error", { allowParens: true }],

            "no-const-assign": "error",
            "no-console": "warn",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-duplicate-imports": "error",
            "no-new-symbol": "error",
            "no-restricted-exports": "error",
            "no-restricted-imports": "error",
            "no-this-before-super": "error",
            "no-useless-computed-key": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-var": "error",
            "object-shorthand": ["error", "always"],
            "prefer-arrow-callback": "error",
            "prefer-const": "error",

            "prefer-destructuring": ["error", { array: false }],

            "prefer-numeric-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "require-yield": "error",
            "rest-spread-spacing": "error",
            "symbol-description": "error",
            "template-curly-spacing": "error",
            "yield-star-spacing": "error",

            "eslint-comments/no-aggregating-enable": "error",
            "eslint-comments/no-duplicate-disable": "error",
            "eslint-comments/no-unlimited-disable": "error",
            "eslint-comments/no-unused-enable": "error",
            "eslint-comments/no-restricted-disable": "error",
            "eslint-comments/require-description": "error",

            "no-secrets/no-secrets": ["error", { tolerance: 6 }],

            "@typescript-eslint/adjacent-overload-signatures": "error",
            "@typescript-eslint/array-type": "error",
            "@typescript-eslint/await-thenable": "error",
            "@typescript-eslint/ban-tslint-comment": "error",

            "@typescript-eslint/ban-ts-comment": [
                "error",
                {
                    "ts-ignore": "allow-with-description",
                    "ts-expect-error": "allow-with-description",
                    "ts-nocheck": "allow-with-description",
                },
            ],

            "@typescript-eslint/class-literal-property-style": "error",
            "@typescript-eslint/consistent-indexed-object-style": [
                "error",
                "index-signature",
            ],
            "@typescript-eslint/consistent-type-assertions": "error",
            "@typescript-eslint/consistent-type-exports": "error",
            "@typescript-eslint/consistent-type-imports": "error",
            "@typescript-eslint/explicit-function-return-type": "error",
            "@typescript-eslint/explicit-member-accessibility": "error",
            "@typescript-eslint/explicit-module-boundary-types": "error",
            "@typescript-eslint/member-ordering": "error",
            "@typescript-eslint/method-signature-style": "error",
            "@typescript-eslint/no-base-to-string": "error",
            "@typescript-eslint/no-confusing-non-null-assertion": "error",
            "@typescript-eslint/no-confusing-void-expression": "error",
            "@typescript-eslint/no-dynamic-delete": "error",
            "@typescript-eslint/no-empty-interface": "error",
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/no-extra-non-null-assertion": "error",
            "@typescript-eslint/no-extraneous-class": "error",

            "@typescript-eslint/no-floating-promises": [
                "error",
                { ignoreVoid: true },
            ],

            "@typescript-eslint/no-for-in-array": "error",
            "@typescript-eslint/no-inferrable-types": "error",
            "@typescript-eslint/no-invalid-void-type": "error",
            "@typescript-eslint/no-meaningless-void-operator": "error",
            "@typescript-eslint/no-misused-new": "error",
            "@typescript-eslint/no-namespace": "error",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
            "@typescript-eslint/no-non-null-asserted-nullish-coalescing":
                "error",
            "@typescript-eslint/no-non-null-assertion": "error",
            "@typescript-eslint/no-redundant-type-constituents": "error",
            "@typescript-eslint/no-this-alias": "error",
            "@typescript-eslint/no-unnecessary-boolean-literal-compare":
                "error",
            "@typescript-eslint/no-unnecessary-qualifier": "error",
            "@typescript-eslint/no-unnecessary-type-arguments": "error",
            "@typescript-eslint/no-unnecessary-type-assertion": "error",
            "@typescript-eslint/no-unnecessary-type-constraint": "error",
            "@typescript-eslint/no-var-requires": "error",
            "@typescript-eslint/non-nullable-type-assertion-style": "error",
            "@typescript-eslint/prefer-as-const": "error",
            "@typescript-eslint/prefer-enum-initializers": "error",
            "@typescript-eslint/prefer-for-of": "error",
            "@typescript-eslint/prefer-function-type": "error",
            "@typescript-eslint/prefer-includes": "error",
            "@typescript-eslint/prefer-literal-enum-member": "error",
            "@typescript-eslint/prefer-namespace-keyword": "error",
            "@typescript-eslint/prefer-nullish-coalescing": "error",
            "@typescript-eslint/prefer-optional-chain": "error",
            "@typescript-eslint/prefer-readonly": "error",
            "@typescript-eslint/prefer-reduce-type-parameter": "error",
            "@typescript-eslint/prefer-regexp-exec": "error",
            "@typescript-eslint/prefer-return-this-type": "error",
            "@typescript-eslint/prefer-string-starts-ends-with": "error",
            "@typescript-eslint/prefer-ts-expect-error": "error",
            "@typescript-eslint/promise-function-async": "error",

            "@typescript-eslint/require-array-sort-compare": [
                "error",
                { ignoreStringArrays: true },
            ],

            "@typescript-eslint/restrict-plus-operands": "error",

            "@typescript-eslint/strict-boolean-expressions": [
                "error",
                {
                    allowString: true,
                    allowNullableString: true,
                    allowNullableBoolean: true,
                },
            ],

            "@typescript-eslint/switch-exhaustiveness-check": "error",
            "@typescript-eslint/triple-slash-reference": "error",
            "@typescript-eslint/typedef": "error",
            "@typescript-eslint/unbound-method": "error",
            "@typescript-eslint/unified-signatures": "error",
            "@typescript-eslint/default-param-last": "error",
            "@typescript-eslint/dot-notation": "error",
            "@typescript-eslint/init-declarations": "error",
            "@typescript-eslint/no-array-constructor": "error",
            "@typescript-eslint/no-dupe-class-members": "error",
            "@typescript-eslint/no-empty-function": "error",
            "@typescript-eslint/no-implied-eval": "error",
            "@typescript-eslint/no-invalid-this": "error",
            "@typescript-eslint/no-loop-func": "error",
            "@typescript-eslint/no-loss-of-precision": "error",
            "@typescript-eslint/no-redeclare": "error",
            "@typescript-eslint/no-restricted-imports": "error",
            "@typescript-eslint/no-shadow": "error",
            "@typescript-eslint/no-unused-expressions": "error",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    args: "all",
                    argsIgnorePattern: "^_",
                    caughtErrors: "all",
                    caughtErrorsIgnorePattern: "^_",
                    destructuredArrayIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                    ignoreRestSiblings: true,
                },
            ],
            "@typescript-eslint/no-use-before-define": "error",
            "@typescript-eslint/no-useless-constructor": "error",
            "@typescript-eslint/no-useless-empty-export": "error",
            "@typescript-eslint/require-await": "error",
            "@typescript-eslint/return-await": "off",
            "react/boolean-prop-naming": "error",
            "react/button-has-type": "error",
            "react/default-props-match-prop-types": "error",
            "react/destructuring-assignment": "error",
            "react/display-name": "error",
            "react/forbid-dom-props": "error",
            "react/forbid-elements": "error",
            "react/forbid-foreign-prop-types": "error",
            "react/forbid-prop-types": "error",

            "react/function-component-definition": [
                "error",
                {
                    namedComponents: "arrow-function",
                    unnamedComponents: "arrow-function",
                },
            ],

            "react/iframe-missing-sandbox": "error",
            "react/hook-use-state": "error",
            "react/no-access-state-in-setstate": "error",
            "react/no-adjacent-inline-elements": "error",
            "react/no-array-index-key": "error",
            "react/no-arrow-function-lifecycle": "error",
            "react/no-children-prop": "error",
            "react/no-danger": "error",
            "react/no-danger-with-children": "error",
            "react/no-deprecated": "error",
            "react/no-did-mount-set-state": ["error", "disallow-in-func"],
            "react/no-did-update-set-state": ["error", "disallow-in-func"],
            "react/no-direct-mutation-state": "error",
            "react/no-find-dom-node": "error",
            "react/no-invalid-html-attribute": "error",
            "react/no-is-mounted": "error",
            "react/no-multi-comp": "error",
            "react/no-namespace": "error",
            "react/no-redundant-should-component-update": "error",
            "react/no-render-return-value": "error",
            "react/no-set-state": "error",
            "react/no-string-refs": "error",
            "react/no-this-in-sfc": "error",
            "react/no-typos": "error",
            "react/no-unescaped-entities": "error",
            "react/no-unknown-property": "error",
            "react/no-unsafe": "error",
            "react/no-unstable-nested-components": "error",
            "react/no-unused-class-component-methods": "error",
            "react/no-unused-prop-types": "error",
            "react/no-unused-state": "error",
            "react/no-will-update-set-state": ["error", "disallow-in-func"],
            "react/prefer-es6-class": "error",
            "react/prefer-exact-props": "error",
            "react/prefer-read-only-props": "error",
            "react/prefer-stateless-function": "error",
            "react/prop-types": "error",
            "react/react-in-jsx-scope": "error",
            "react/require-optimization": "error",
            "react/require-render-return": "error",
            "react/self-closing-comp": "error",
            "react/sort-comp": "error",
            "react/sort-prop-types": "error",
            "react/state-in-constructor": ["error", "never"],
            "react/static-property-placement": "error",
            "react/style-prop-object": "error",
            "react/void-dom-elements-no-children": "error",
            "react/jsx-boolean-value": "error",
            "react/jsx-child-element-spacing": "error",
            "react/jsx-closing-bracket-location": "error",
            "react/jsx-closing-tag-location": "error",

            "react/jsx-curly-brace-presence": [
                "error",
                {
                    props: "ignore",
                    children: "always",
                    propElementValues: "always",
                },
            ],

            "react/jsx-curly-newline": "off",
            "react/jsx-curly-spacing": "error",
            "react/jsx-equals-spacing": "error",

            "react/jsx-filename-extension": [
                "error",
                { extensions: [".jsx", ".tsx"] },
            ],

            "react/jsx-first-prop-new-line": ["error", "multiline"],
            "react/jsx-fragments": ["error", "syntax"],
            "react/jsx-handler-names": "error",
            "react/jsx-indent-props": ["error", 4],
            "react/jsx-key": "error",

            "react/jsx-max-depth": ["error", { max: 25 }],

            "react/jsx-no-bind": [
                "error",
                { allowArrowFunctions: true, ignoreRefs: true },
            ],

            "react/jsx-no-comment-textnodes": "error",
            "react/jsx-no-constructed-context-values": "error",
            "react/jsx-no-duplicate-props": "error",
            "react/jsx-no-literals": "error",
            "react/jsx-no-script-url": "error",
            "react/jsx-no-target-blank": "error",
            "react/jsx-no-useless-fragment": "error",
            "react/jsx-pascal-case": "error",
            "react/jsx-props-no-multi-spaces": "error",
            "react/sort-default-props": "error",
            "react/jsx-sort-props": "error",
            "react/jsx-tag-spacing": "error",
            "react/jsx-uses-react": "error",
            "react/jsx-uses-vars": "error",
            "react/jsx-wrap-multilines": "error",
            "simple-import-sort/exports": "error",
            "simple-import-sort/imports": "error",
            "sonarjs/prefer-immediate-return": "off",
            "sonarjs/cognitive-complexity": "off",
            "unicorn/prefer-module": "off",

            "unicorn/filename-case": [
                "error",
                { cases: { pascalCase: true, camelCase: true } },
            ],

            "unicorn/no-nested-ternary": "off",
            "unicorn/no-useless-undefined": "off",
            "compat/compat": "off",

            "perfectionist/sort-imports": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-named-exports": "off",

            "perfectionist/sort-enums": [
                "error",
                { type: "natural", order: "asc" },
            ],

            "perfectionist/sort-exports": "off",
            "perfectionist/sort-classes": "off",
            "file-progress/activate": 1,
            "xss/no-mixed-html": "off",
            "more/no-void-map": 2,
            "more/no-c-like-loops": 2,
            "more/prefer-includes": 2,
            "more/no-then": 2,
            "more/no-window": [2],
            "more/no-numeric-endings-for-variables": 2,
            "more/no-filter-instead-of-find": 2,
            "more/force-native-methods": 2,
            "more/no-duplicated-chains": 2,
            "more/classbody-starts-with-newline": "off",
            "more/no-hardcoded-password": "off",
            "more/no-hardcoded-configuration-data": 2,
            "write-good-comments/write-good-comments": "warn",
            "@next/next/no-img-element": "off",
            "sonarjs/different-types-comparison": "off",
            "sonarjs/todo-tag": "off",
            "sonarjs/no-misused-promises": "off",
            "sonarjs/sonar-no-unused-vars": "off",
            "no-unsanitized/method": "error",
            "no-unsanitized/property": "error",
            "import-access/jsdoc": "error",
            "barrel-files/avoid-barrel-files": "error",
            "barrel-files/avoid-importing-barrel-files": "error",
            "barrel-files/avoid-namespace-import": "error",
            "barrel-files/avoid-re-export-all": "error",
            "eslint-comments/no-use": "off",
            "import/no-unresolved": "off",
            "prettier/prettier": "off",
            "github/filenames-match-regex": "off",
            "jsdoc/require-hyphen-before-param-description": [
                "error",
                "always",
            ],
            "jsdoc/require-template": "error",
            "jsdoc/informative-docs": ["error", { excludedTags: ["example"] }],
            "jsdoc/sort-tags": "error",
            "jsdoc/require-param-type": "off",
            "jsdoc/convert-to-jsdoc-comments": "off",
            "jsdoc/no-undefined-types": "off",
            "jsdoc/require-asterisk-prefix": "error",
            "jsdoc/imports-as-dependencies": "error",
            "jsdoc/check-access": "error",
            "jsdoc/check-alignment": "error",
            "jsdoc/check-indentation": "error",
            "jsdoc/check-line-alignment": "error",
            "jsdoc/check-param-names": "error",
            "jsdoc/check-template-names": "error",
            "jsdoc/check-property-names": "error",
            "jsdoc/check-syntax": "error",
            "jsdoc/check-tag-names": ["error", { definedTags: ["source"] }],
            "jsdoc/check-types": "error",
            "jsdoc/check-values": "error",
            "jsdoc/empty-tags": "error",
            "jsdoc/implements-on-classes": "error",
            "jsdoc/match-description": "error",
            "jsdoc/multiline-blocks": "error",
            "jsdoc/no-bad-blocks": "error",
            "jsdoc/no-blank-block-descriptions": "error",
            "jsdoc/no-defaults": "error",
            "jsdoc/no-missing-syntax": "off",
            "jsdoc/no-multi-asterisks": "error",
            "jsdoc/no-restricted-syntax": ["error", { contexts: ["any"] }],
            "jsdoc/no-types": "error",
            "jsdoc/require-description": "error",
            "jsdoc/require-description-complete-sentence": "error",
            "jsdoc/require-file-overview": "error",
            "jsdoc/require-jsdoc": [
                "error",
                {
                    require: {
                        FunctionDeclaration: true,
                        MethodDefinition: true,
                        ClassDeclaration: true,
                        ClassExpression: true,
                        ArrowFunctionExpression: true,
                        FunctionExpression: true,
                    },
                },
            ],
            "jsdoc/require-param": [
                "error",
                { checkRestProperty: true, useDefaultObjectProperties: true },
            ],
            "jsdoc/require-param-description": "error",
            "jsdoc/require-param-name": "error",
            "jsdoc/require-property": "error",
            "jsdoc/require-property-description": "error",
            "jsdoc/require-property-name": "error",
            "jsdoc/require-property-type": "error",
            "jsdoc/require-returns": "error",
            "jsdoc/require-returns-check": "error",
            "jsdoc/require-returns-description": "error",
            "jsdoc/require-returns-type": "off",
            "jsdoc/require-throws": "error",
            "jsdoc/require-yields": "error",
            "jsdoc/require-yields-check": "error",
            "jsdoc/tag-lines": "error",
            "jsdoc/valid-types": "error",
            "sonarjs/function-name": "error",
            "sonarjs/variable-name": "error",
            "sonarjs/elseif-without-else": "off",
            "sonarjs/nested-control-flow": "error",
            "sonarjs/too-many-break-or-continue-in-loop": "error",
            "sonarjs/no-nested-incdec": "error",
            "sonarjs/no-collapsible-if": "error",
            "sonarjs/expression-complexity": "error",
            "sonarjs/no-unused-function-argument": "error",
            "sonarjs/no-duplicate-string": "error",
            "sonarjs/no-sonar-comments": "error",
            "sonarjs/no-variable-usage-before-declaration": "error",
            "sonarjs/array-constructor": "error",
            "sonarjs/no-function-declaration-in-block": "error",
            "sonarjs/for-in": "error",
            "sonarjs/cyclomatic-complexity": "error",
            "sonarjs/no-undefined-assignment": "off",
            "sonarjs/no-wildcard-import": "error",
            "sonarjs/no-built-in-override": "error",
            "sonarjs/prefer-object-literal": "error",
            "sonarjs/strings-comparison": "error",
            "sonarjs/file-name-differ-from-class": "error",
            "sonarjs/no-incorrect-string-concat": "error",
            "sonarjs/shorthand-property-grouping": "off",
            "sonarjs/arguments-usage": "error",
            "sonarjs/destructuring-assignment-syntax": "error",
            "sonarjs/arrow-function-convention": "off",
            "sonarjs/class-prototype": "error",
            "sonarjs/no-require-or-define": "error",
            "sonarjs/operation-returning-nan": "error",
            "sonarjs/values-not-convertible-to-numbers": "error",
            "sonarjs/non-number-in-arithmetic-expression": "error",
            "sonarjs/declarations-in-global-scope": "error",
            "sonarjs/no-inconsistent-returns": "error",
            "sonarjs/no-reference-error": "error",
            "sonarjs/no-for-in-iterable": "error",
            "sonarjs/no-return-type-any": "error",
            "sonarjs/no-implicit-dependencies": "error",
            "sonarjs/bool-param-default": "error",
            "sonarjs/unicode-aware-regex": "error",
            "sonarjs/aws-iam-all-resources-accessible": "error",
            "unicorn/better-regex": "error",
            "unicorn/consistent-destructuring": "error",
            "unicorn/custom-error-definition": "error",
            "unicorn/no-unused-properties": "error",
            "unicorn/require-post-message-target-origin": "error",
            "unicorn/string-content": "error",
            "observers/no-missing-unobserve-or-disconnect": "error",
            "observers/matching-unobserve-target": "error",
            "unicorn/no-keyword-prefix": [
                "error",
                { disallowedPrefixes: ["new", "let", "const"] },
            ],
            "jsdoc/require-example": "off",
            "fsecond/prefer-destructured-optionals": "off",
            "github/no-dataset": "off",
            "write-good-comments/write-good-comments": [
                "warn",
                {
                    passive: true,
                    illusion: true,
                    so: true,
                    thereIs: true,
                    weasel: true,
                    adverb: true,
                    tooWordy: true,
                    cliches: true,
                    eprime: false,
                    whitelist: ["equivalent"],
                },
            ],
            "@typescript-eslint/non-nullable-type-assertion-style": "off",
        },
    },
    {
        files: ["**/*.js", "**/*.ts"],

        rules: {
            "jsdoc/require-example": "error",
            "more/no-void-map": "off",
            "i18n-text/no-en": "off",
            "tsdoc/syntax": "warn",
            "@typescript-eslint/no-unsafe-assignment": "error",
            "@typescript-eslint/no-unsafe-call": "error",
            "@typescript-eslint/no-unsafe-member-access": "error",
            "@typescript-eslint/no-unsafe-return": "error",
            "@typescript-eslint/no-var-requires": "error",

            "@typescript-eslint/strict-boolean-expressions": [
                "error",
                {
                    allowString: true,
                    allowNullableString: true,
                    allowNullableBoolean: true,
                },
            ],

            "import/named": "error",
            "import/no-commonjs": "error",
            "import/unambiguous": "error",
            "n/global-require": "error",
            "n/no-unsupported-features/es-builtins": "error",
            "n/no-unsupported-features/es-syntax": "error",
            "n/no-unsupported-features/node-builtins": "error",
            "observers/no-missing-unobserve-or-disconnect": "error",
            "observers/matching-unobserve-target": "error",
        },
    },
]);
