/* eslint-disable import/no-namespace -- disabled */
/* eslint-disable sort-keys -- disabled */
/* eslint-disable node/no-unpublished-import -- disabled */

import withMT from "@material-tailwind/react/utils/withMT";
import typography from "@tailwindcss/typography";
import { withAnimations } from "animated-tailwindcss";
import * as daisyui from "daisyui";
import type { Config } from "tailwindcss";

const config: Config = withAnimations(
    withMT({
        content: [
            "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
            "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
            "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
            "./src/modules/**/*.{js,ts,jsx,tsx,mdx}",
            "./src/common/components/**/*.{js,ts,jsx,tsx,mdx}",
            "./src/common/components/*.{js,ts,jsx,tsx,mdx}",
            "node_modules/flowbite-react/lib/esm/**/*.js",
            "node_modules/flowbite/dist/flowbite.min.js",
        ],
        plugins: [typography(), daisyui.default],
        safelist: [
            "btn-success",
            "btn-primary",
            "btn-neutral",
            "btn-disabled",
            "badge-primary",
            "badge-success",
            "badge-warning",
            "badge-error",
            "badge-info",
            "badge-neutral",
            "chat-start",
            "chat-end",
            "tooltip-open",
            "input-error",
            "input-info",
            "input-success",
            "input-primary",
            "bg-success",
            "bg-error",
            "text-success",
            "text-error",
        ],
        theme: {
            extend: {
                colors: {
                    quantumBlue: "#009ede",
                    quantumBlueHover: "#52cdff",
                    quantumBrightGray: "#e3e3e3",
                    quantumBrightWhite: "#F8F8F8",
                    quantumDarkBlue: "rgba(0, 159, 223, 0.05)",
                    quantumGray: "#5a5a5a",
                    quantumGreen: "#24bb0b",
                    quantumGreenHover: "#66f54e",
                    quantumMediumGray: "#b4b4b4",
                    quantumRed: "#FF4E00",
                    quantumWhite: "#E3F2FC",
                },
                backgroundImage: {
                    "gradient-conic":
                        "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
                    "gradient-radial":
                        "radial-gradient(var(--tw-gradient-stops))",
                },
                borderColor: {
                    filePreviewActive: "#009FDF",
                },
                borderWidth: {
                    "1": "1px",
                },
                brightness: {
                    "107": "107%",
                },
                height: {
                    "1/8": "12.5%",
                    "1/7": "14.28571%",
                    "1/6": "16.66667%",
                    "2/6": "33.33333%",
                    "3/6": "50%",
                    "4/6": "66.66667%",
                    "5/6": "83.33333%",
                    "3.5/10": "35%",
                    "2/10": "20%",
                    "1/10": "10%",
                    "8/10": "80%",
                    "9/10": "90%",
                    "1.5/10": "15%",
                    "1.7/10": "17%",
                    "3/10": "30%",
                    "1.25/10": "12.5%",
                    "1.55/10": "15.5%",
                },
                flexGrow: {
                    "2": "2",
                    "3": "3",
                },
                fontSize: {
                    calcsm: "calc(0.5rem + 1vw)",
                    calcmd: "calc(2rem + 5vw)",
                    calclg: "calc(3.5rem + 20vw)",
                    smBase: ["0.95rem", "1.5rem"],
                    xxs: ["0.65rem", ".90rem"],
                    xxxs: ["0.55rem", ".80rem"],
                    xxxxs: ["0.5rem", "0.70rem"],
                },
                fontWeight: {
                    superbold: "900",
                },
                gap: {
                    "-1": "-0.25rem",
                    "-2": "-0.5rem",
                    "-3": "-0.75rem",
                    "1/3": "33.333%",
                    "1/2": "50%",
                    full: "100%",
                },
                left: {
                    "3.5/4": "87.5%",
                    "3.75/4": "93.75%",
                    "150": "150%",
                    "133": "133.333333%",
                    "120": "120%",
                    "116": "116.6666664%",
                    "114": "114.2857142%",
                },
                minHeight: {
                    "0.5": "0.125rem",
                    "1": "0.25em",
                    "1.5": "0.375rem",
                    "2": "0.5rem",
                    "2.5": "0.625rem",
                    "3": "0.75rem",
                    "3.5": "0.875rem",
                    "4": "1rem",
                    "5": "1.25rem",
                    "6": "1.5rem",
                    "7": "1.75rem",
                    "8": "2rem",
                    "9": "2.25rem",
                    "10": "2.5rem",
                    "11": "2.75rem",
                    "12": "3rem",
                    "14": "3.5rem",
                    "16": "4rem",
                    "18": "4.5rem",
                    "20": "5rem",
                    "22": "5.5rem",
                    "24": "6rem",
                    "26": "6.5rem",
                    "28": "7rem",
                    "30": "7.5rem",
                    "35": "8.25rem",
                    "40": "9rem",
                    "45": "9.75rem",
                    "50": "10.5rem",
                    "60": "12rem",
                    "70": "13.5rem",
                    "80": "15rem",
                    "90": "16.5rem",
                    "100": "18rem",
                    "10vh": "10vh",
                    "20vh": "20vh",
                    "30vh": "30vh",
                    "40vh": "40vh",
                    "50vh": "50vh",
                    "55vh": "55vh",
                    "60vh": "60vh",
                    "65vh": "65vh",
                    "70vh": "70vh",
                    "80vh": "80vh",
                    "90vh": "90vh",
                    "100vh": "100vh",
                },
                maxHeight: {
                    "1/8": "12.5%",
                    "1/7": "14.28571%",
                    "1/6": "16.66667%",
                    "2/6": "33.33333%",
                    "3/6": "50%",
                    "4/6": "66.66667%",
                    "5/6": "83.33333%",
                    "3.5/10": "35%",
                    "2/10": "20%",
                    "1/10": "10%",
                    "1.5/10": "15%",
                    "1.7/10": "17%",
                    "3/10": "30%",
                    "1.25/10": "12.5%",
                    "1.55/10": "15.5%",
                },
                maxWidth: {
                    "1vw": "1vw",
                    "2vw": "2vw",
                    "3vw": "3vw",
                    "4vw": "4vw",
                    "5vw": "5vw",
                    "6vw": "6vw",
                    "7vw": "7vw",
                    "8vw": "8vw",
                    "9vw": "9vw",
                    "10vw": "10vw",
                    "15vw": "15vw",
                    "20vw": "20vw",
                    "25vw": "25vw",
                    "50vw": "50vw",
                    "75vw": "75vw",
                    "100vw": "100vw",
                },
                minWidth: {
                    "1vw": "1vw",
                    "2vw": "2vw",
                    "3vw": "3vw",
                    "4vw": "4vw",
                    "5vw": "5vw",
                    "6vw": "6vw",
                    "7vw": "7vw",
                    "8vw": "8vw",
                    "9vw": "9vw",
                    "10vw": "10vw",
                    "15vw": "15vw",
                    "20vw": "20vw",
                    "25vw": "25vw",
                    "50vw": "50vw",
                    "75vw": "75vw",
                    "100vw": "100vw",
                    "3.5/10": "35%",
                    "2/10": "20%",
                    "1/10": "10%",
                    "1.5/10": "15%",
                    "1.7/10": "17%",
                    "3/10": "30%",
                    "1.25/10": "12.5%",
                    "1.55/10": "15.5%",
                },
                padding: {
                    "4.5": "1.15rem",
                },
                right: {
                    ".5": ".125rem",
                },
                top: {
                    "3/4": "75%",
                    "8/9": "90%",
                },
                width: {
                    "1/8": "12.5%",
                    "1/7": "14.28571%",
                },
                zIndex: {
                    "60": "60",
                    "70": "70",
                    "80": "80",
                    max: "9999",
                },
            },
            flexBasis: {
                "1/4": "25%",
                "2/4": "50%",
                "3/4": "75%",
                "4/4": "100%",
            },
            fontFamily: {
                sans: [
                    "var(--poppins)",
                    "var(--bebas_neue)",
                    "var(--jetbrains)",
                    "var(--quicksand)",
                    "var(--source_code_pro)",
                    "cursive",
                    "sans-serif",
                ],
            },
        },
    }),
) as Config;

export default config;
